"""The licences file has one entry for every package the lockfiles put in the image.

``THIRD_PARTY_LICENSES.md`` is generated by ``scripts/third_party_licenses.py`` from
``uv.lock`` and ``web/package-lock.json``. These tests read committed files only (the
runtime Python set through an offline ``uv export``), so they run on every pipeline and
never touch the network. What they prove is coverage: every package at its locked
version has exactly one entry, with licence text in it, and nothing else does. They do
not prove an entry's text is what the artifact holds; ``--check`` proves that, and it
needs the network.

A dependency added, removed or bumped without regenerating the file fails T1 or T2,
naming the package.
"""

from __future__ import annotations

import importlib.util
import json
import sys
import tomllib
from pathlib import Path
from types import ModuleType

import pytest

pytestmark = pytest.mark.structural

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "third_party_licenses.py"
LICENSES = REPO_ROOT / "THIRD_PARTY_LICENSES.md"
PACKAGE_LOCK = REPO_ROOT / "web" / "package-lock.json"


def _script() -> ModuleType:
    spec = importlib.util.spec_from_file_location("third_party_licenses", SCRIPT)
    assert spec is not None and spec.loader is not None, f"cannot load {SCRIPT}"
    module = importlib.util.module_from_spec(spec)
    # A dataclass looks its module up in sys.modules while it is being defined.
    sys.modules["third_party_licenses"] = module
    spec.loader.exec_module(module)
    return module


tpl = _script()


@pytest.fixture(scope="module")
def expected() -> set[tuple[str, str, str]]:
    """Every (ecosystem, name, version) the lockfiles say the image redistributes."""
    lock = json.loads(PACKAGE_LOCK.read_text())
    return tpl.expected_entries(tpl.runtime_python_packages(), tpl.npm_packages(lock))


@pytest.fixture(scope="module")
def text() -> str:
    return LICENSES.read_text()


def test_t1_every_locked_package_has_exactly_one_entry_at_its_version(
    expected: set[tuple[str, str, str]], text: str
) -> None:
    coverage = tpl.coverage(expected, text)
    assert coverage.missing == [], (
        "these packages are in the lockfiles with no entry in THIRD_PARTY_LICENSES.md; "
        "regenerate it with `uv run python scripts/third_party_licenses.py`: "
        f"{coverage.missing}"
    )
    assert coverage.duplicated == [], f"these have more than one entry: {coverage.duplicated}"


def test_t2_no_entry_names_a_package_the_lockfiles_no_longer_hold(
    expected: set[tuple[str, str, str]], text: str
) -> None:
    coverage = tpl.coverage(expected, text)
    assert coverage.unexpected == [], (
        "these entries name a package or version the lockfiles do not hold; regenerate "
        f"the file: {coverage.unexpected}"
    )


def test_t3_every_entry_carries_licence_text(text: str) -> None:
    empty = [
        f"{entry.ecosystem} {entry.name} {entry.version}"
        for entry in tpl.parse(text)
        if not any(body.strip() for _, body in entry.files)
    ]
    assert empty == []


def test_t4_a_new_dependency_without_an_entry_fails_naming_it() -> None:
    """On synthetic inputs, independent of the real lockfiles."""
    react = {
        "version": "19.0.0",
        "resolved": "https://registry.npmjs.org/react/-/react-19.0.0.tgz",
        "integrity": "sha512-x",
    }
    lock: dict[str, object] = {"packages": {"": {}, "node_modules/react": react}}
    python = [("idna", "3.10")]
    entries = [
        tpl.Entry("python", "idna", "3.10", "BSD-3-Clause", "https://x/idna.whl", (("L", "t"),)),
        tpl.Entry("npm", "react", "19.0.0", "MIT", "https://x/react.tgz", (("L", "t"),)),
    ]
    text = tpl.render(entries)
    clean = tpl.coverage(tpl.expected_entries(python, tpl.npm_packages(lock)), text)
    assert (clean.missing, clean.duplicated, clean.unexpected) == ([], [], [])

    packages = lock["packages"]
    assert isinstance(packages, dict)
    packages["node_modules/left-pad"] = {"version": "1.3.0", "resolved": "r", "integrity": "i"}
    added = tpl.coverage(tpl.expected_entries(python, tpl.npm_packages(lock)), text)
    assert added.missing == ["npm `left-pad` 1.3.0"]


def test_t5_every_override_names_a_package_at_its_locked_version(
    expected: set[tuple[str, str, str]],
) -> None:
    overrides = tpl.load_overrides(tpl.OVERRIDES)
    assert overrides, "the overrides file holds no override"
    assert tpl.override_problems(overrides, expected) == []


def test_t5_an_override_for_a_version_no_longer_locked_is_refused() -> None:
    raw = tomllib.loads(
        '[[override]]\necosystem = "python"\npackage = "flatbuffers"\nversion = "1.0"\n'
        '[[override.file]]\nurl = "https://x/LICENSE"\nsha256 = "00"\n'
    )
    overrides = tpl.parse_overrides(raw)
    problems = tpl.override_problems(overrides, {("python", "flatbuffers", "25.12.19")})
    assert problems == ["override for python `flatbuffers` 1.0: the lockfiles hold no such version"]


def test_t6_the_only_headings_are_the_title_and_one_per_entry(text: str) -> None:
    """Read as the checker reads it: every line that starts with ``#`` is a heading, and
    every backticked word in a heading is a package it counts."""
    stray = [
        line
        for line in text.splitlines()
        if line.startswith("#") and line != tpl.TITLE and not tpl.HEADING.match(line)
    ]
    assert stray == [], f"lines the checker would read as headings: {stray[:5]}"
    named = tpl.notices_coverage.named_in_notices(text)
    entries = {tpl.notices_coverage.normalise(entry.name) for entry in tpl.parse(text)}
    assert named == entries
