"""Generate THIRD_PARTY_LICENSES.md from the lockfiles.

Publishing the image is redistribution, and most of the licences of the packages it
carries require their licence text and copyright notice to travel with every copy. This
writes one entry per package the image redistributes, at the version the lockfile
records, holding the licence files of the exact artifact the lockfile records:

- every runtime Python package in ``uv.lock`` (the offline ``uv export`` without
  development dependencies, so including the few that install only on Windows or in a
  browser, because the list is the lockfile's and not one platform's);
- every npm package ``scripts/notices_coverage.py`` counts, through its
  ``npm_production_entries``, so the release check and this file judge by one rule.

It reads the two lockfiles and nothing installed. Each artifact is downloaded from the
URL the lockfile records and refused unless its hash matches the lockfile's. Archive
members are read in memory, never extracted to disk. Where a package's text comes from,
in order:

1. Python: every file under the wheel's ``.dist-info/licenses/`` and every licence file
   directly in ``.dist-info/``; if there are none, every licence file anywhere in the
   wheel; if there are none, every licence file in the lock-recorded sdist.
2. npm: the licence files at the tarball's package root.
3. Otherwise an override from ``scripts/third_party_licenses.toml``: upstream files for
   one package at one version, each pinned by its sha256.
4. Otherwise it exits 1 naming the package. It also exits 1 for an override whose
   package or version the lockfiles no longer hold.

Texts are reproduced as published, with CRLF and lone CR turned into LF and exactly one
final newline, and indented four spaces so no line of a licence can read as a heading.
Where a text names no copyright holder, the entry names none.

    uv run python scripts/third_party_licenses.py            # write the file
    uv run python scripts/third_party_licenses.py --check    # exit 1 if it is stale

Both need the network. ``tests/test_third_party_licenses.py`` checks, offline, that the
committed file has an entry for every package at its locked version.
"""

from __future__ import annotations

import argparse
import base64
import email.parser
import hashlib
import io
import json
import os
import re
import subprocess
import sys
import tarfile
import tempfile
import tomllib
import urllib.request
import zipfile
from collections import Counter
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
UV_LOCK = REPO_ROOT / "uv.lock"
PACKAGE_LOCK = REPO_ROOT / "web" / "package-lock.json"
OVERRIDES = REPO_ROOT / "scripts" / "third_party_licenses.toml"
OUTPUT = REPO_ROOT / "THIRD_PARTY_LICENSES.md"

sys.path.insert(0, str(REPO_ROOT / "scripts"))

import notices_coverage  # noqa: E402

TITLE = "# Third-party licences"

INTRODUCTION = (
    "This file is generated by `scripts/third_party_licenses.py` from `uv.lock` and\n"
    "`web/package-lock.json`, and is not edited by hand: a dependency change regenerates it\n"
    "with `uv run python scripts/third_party_licenses.py`, in the same commit.\n"
)

#: An entry's heading: the package in backticks, which is what the notices check counts,
#: and its version. No other heading in the file carries backticks.
HEADING = re.compile(r"^## `(?P<name>[^`\s]+)` (?P<version>\S+)$")

#: The line under an entry's heading: ecosystem, declared licence, and where the text
#: was taken from.
ORIGIN = re.compile(
    r"^Ecosystem: (?P<ecosystem>python|npm)\. Declared licence: (?P<licence>.*)\. "
    r"Source: (?P<source>.+)$"
)

FILE_LINE = "File: "
INDENT = "    "

#: Characters ``str.splitlines`` breaks a line on, other than ``\n`` and ``\r``. The
#: notices check reads headings with ``splitlines``, so one of these inside a licence
#: text would start an unindented line that could read as a heading.
OTHER_LINE_BREAKS = frozenset("\x0b\x0c\x1c\x1d\x1e\x85  ")

#: A file whose name starts like this carries third-party notices: ``onnxruntime``'s
#: ThirdPartyNotices.txt, ``rolldown``'s THIRD-PARTY-LICENSE.
THIRD_PARTY_PREFIXES = ("third-party", "third_party", "thirdparty")


class GenerationError(Exception):
    """Something the generator will not paper over. The message names the package."""


@dataclass(frozen=True)
class Entry:
    ecosystem: str
    name: str
    version: str
    licence: str
    source: str
    files: tuple[tuple[str, str], ...]

    @property
    def key(self) -> tuple[str, str, str]:
        return (self.ecosystem, self.name, self.version)


@dataclass(frozen=True)
class Override:
    ecosystem: str
    package: str
    version: str
    files: tuple[tuple[str, str], ...]  # (url, sha256)


@dataclass(frozen=True)
class Coverage:
    missing: list[str]
    duplicated: list[str]
    unexpected: list[str]


def describe(key: tuple[str, str, str]) -> str:
    ecosystem, name, version = key
    return f"{ecosystem} `{name}` {version}"


# The packages the image redistributes, from the lockfiles.


def runtime_python_packages(root: Path = REPO_ROOT) -> list[tuple[str, str]]:
    """Every runtime package in ``uv.lock``, as (name, version). The one definition."""
    result = subprocess.run(
        ["uv", "export", "--frozen", "--no-dev", "--no-hashes", "--no-emit-project"],
        cwd=root,
        env={**os.environ, "UV_OFFLINE": "1"},
        capture_output=True,
        text=True,
        timeout=120,
    )
    if result.returncode != 0:
        raise GenerationError(f"uv export failed: {result.stderr.strip()}")
    requirement = re.compile(r"^([A-Za-z0-9][A-Za-z0-9._-]*)==([^\s;]+)")
    found = {
        (match.group(1), match.group(2))
        for line in result.stdout.splitlines()
        if (match := requirement.match(line))
    }
    return sorted(found)


def npm_packages(lock: dict[str, object]) -> list[tuple[str, str]]:
    """Every npm package the notices check counts, as (name, version)."""
    return [(e.name, e.version) for e in notices_coverage.npm_production_entries(lock)]


def expected_entries(
    python: list[tuple[str, str]], npm: list[tuple[str, str]]
) -> set[tuple[str, str, str]]:
    return {("python", name, version) for name, version in python} | {
        ("npm", name, version) for name, version in npm
    }


# The file's format: rendering, parsing, and holding it to the lockfiles.


def normalise_text(text: str, where: str) -> str:
    """LF line endings and exactly one final newline; refuse other line breaks."""
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    odd = sorted(OTHER_LINE_BREAKS.intersection(text))
    if odd:
        raise GenerationError(
            f"{where} contains a line break other than LF or CR ({[hex(ord(c)) for c in odd]}),"
            " which would start an unindented line in the licences file"
        )
    return text.rstrip("\n") + "\n"


def render(entries: list[Entry]) -> str:
    lines = [TITLE, "", INTRODUCTION.rstrip("\n")]
    for entry in sorted(entries, key=lambda e: e.key):
        lines += [
            "",
            f"## `{entry.name}` {entry.version}",
            "",
            f"Ecosystem: {entry.ecosystem}. Declared licence: {entry.licence}. "
            f"Source: {entry.source}",
        ]
        for path, text in entry.files:
            lines += ["", f"{FILE_LINE}{path}", ""]
            lines += [INDENT + line if line else "" for line in text.rstrip("\n").split("\n")]
    return "\n".join(lines) + "\n"


def parse(text: str) -> list[Entry]:
    """The entries of a rendered file, read back."""
    entries: list[Entry] = []
    current: dict[str, object] | None = None
    files: list[tuple[str, list[str]]] = []

    def close() -> None:
        if current is None:
            return
        entries.append(
            Entry(
                str(current["ecosystem"]),
                str(current["name"]),
                str(current["version"]),
                str(current["licence"]),
                str(current["source"]),
                tuple(
                    (path, "\n".join(body).strip("\n") + "\n" if body else "")
                    for path, body in files
                ),
            )
        )

    for line in text.splitlines():
        heading = HEADING.match(line)
        if heading:
            close()
            current = {**heading.groupdict(), "ecosystem": "", "licence": "", "source": ""}
            files = []
        elif current is None:
            continue
        elif (origin := ORIGIN.match(line)) and not files:
            current.update(origin.groupdict())
        elif line.startswith(FILE_LINE):
            files.append((line[len(FILE_LINE) :], []))
        elif files and (line.startswith(INDENT) or not line):
            files[-1][1].append(line[len(INDENT) :])
    close()
    return entries


def coverage(expected: set[tuple[str, str, str]], text: str) -> Coverage:
    counts = Counter(entry.key for entry in parse(text))
    return Coverage(
        missing=[describe(key) for key in sorted(expected) if key not in counts],
        duplicated=[describe(key) for key, n in sorted(counts.items()) if n > 1],
        unexpected=[describe(key) for key in sorted(counts) if key not in expected],
    )


# Overrides.


def parse_overrides(raw: dict[str, object]) -> list[Override]:
    items = raw.get("override", [])
    if not isinstance(items, list):
        raise GenerationError("the overrides file's `override` is not a list of tables")
    overrides = []
    for item in items:
        files = tuple((str(f["url"]), str(f["sha256"])) for f in item.get("file", []))
        overrides.append(
            Override(str(item["ecosystem"]), str(item["package"]), str(item["version"]), files)
        )
    return overrides


def load_overrides(path: Path = OVERRIDES) -> list[Override]:
    return parse_overrides(tomllib.loads(path.read_text()))


def override_problems(overrides: list[Override], expected: set[tuple[str, str, str]]) -> list[str]:
    problems = []
    for override in overrides:
        key = (override.ecosystem, override.package, override.version)
        if key not in expected:
            problems.append(f"override for {describe(key)}: the lockfiles hold no such version")
        if not override.files:
            problems.append(f"override for {describe(key)}: names no file")
    return problems


# Artifacts: download, verify, read.


def fetch(url: str, cache: Path) -> bytes:
    target = cache / hashlib.sha256(url.encode()).hexdigest()[:16] / url.rsplit("/", 1)[-1]
    if target.is_file():
        return target.read_bytes()
    with urllib.request.urlopen(url, timeout=120) as response:
        data: bytes = response.read()
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(data)
    return data


def verified(url: str, expected: str, cache: Path, package: str) -> bytes:
    """The artifact at ``url``, refused unless it matches the lockfile's hash.

    ``expected`` is ``sha256:<hex>`` (uv), ``sha512-<base64>`` (npm), or bare hex sha256
    (an override)."""
    data = fetch(url, cache)
    if expected.startswith("sha512-"):
        actual = "sha512-" + base64.b64encode(hashlib.sha512(data).digest()).decode()
    elif expected.startswith("sha256:"):
        actual = "sha256:" + hashlib.sha256(data).hexdigest()
    else:
        actual = hashlib.sha256(data).hexdigest()
    if actual != expected:
        raise GenerationError(f"{package}: {url} does not match its recorded hash")
    return data


def is_licence_file(path: str) -> bool:
    name = path.rsplit("/", 1)[-1]
    if not name or name.endswith(".py"):
        return False
    return bool(notices_coverage.LICENCE_FILE.search(name)) or name.lower().startswith(
        THIRD_PARTY_PREFIXES
    )


def zip_files(data: bytes) -> dict[str, bytes]:
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        return {
            info.filename: archive.read(info) for info in archive.infolist() if not info.is_dir()
        }


def tar_files(data: bytes, wanted: Callable[[str], bool]) -> dict[str, bytes]:
    """Regular files of a gzipped tarball whose path ``wanted(path)`` accepts."""
    found = {}
    with tarfile.open(fileobj=io.BytesIO(data), mode="r:gz") as archive:
        for member in archive.getmembers():
            if member.isfile() and wanted(member.name):
                handle = archive.extractfile(member)
                if handle is not None:
                    found[member.name] = handle.read()
    return found


def decode(data: bytes, where: str) -> str:
    try:
        return data.decode("utf-8")
    except UnicodeDecodeError as error:
        raise GenerationError(f"{where} is not UTF-8: {error}") from error


def one_line(value: str) -> str:
    return " ".join(value.split())


def python_licence(metadata: str) -> str:
    """The licence a distribution declares: its expression, a short ``License``, or its
    classifiers."""
    message = email.parser.Parser().parsestr(metadata)
    expression = message.get("License-Expression")
    if expression:
        return one_line(expression)
    declared = (message.get("License") or "").strip()
    if declared and "\n" not in declared and len(declared) <= 100:
        return one_line(declared)
    classifiers = [
        c.split("::")[-1].strip()
        for c in message.get_all("Classifier") or []
        if c.startswith("License ::")
    ]
    return ", ".join(classifiers) if classifiers else "not declared"


def pick_wheel(wheels: list[dict[str, str]]) -> dict[str, str]:
    """A pure wheel, else a manylinux x86_64 one (CPython 3.13's first), else the first."""

    def name(wheel: dict[str, str]) -> str:
        return wheel["url"].rsplit("/", 1)[-1]

    pure = [w for w in wheels if name(w).endswith("-none-any.whl")]
    if pure:
        return pure[0]
    linux = [w for w in wheels if "manylinux" in name(w) and "x86_64" in name(w)]
    preferred = [w for w in linux if "-cp313-cp313-" in name(w)]
    return (preferred or linux or wheels)[0]


def uv_lock_packages(path: Path = UV_LOCK) -> dict[tuple[str, str], dict[str, object]]:
    lock = tomllib.loads(path.read_text())
    return {(str(p["name"]), str(p["version"])): p for p in lock["package"]}


def python_entry(
    name: str,
    version: str,
    locked: dict[str, object],
    overrides: dict[tuple[str, str, str], Override],
    cache: Path,
) -> Entry:
    where = f"python `{name}` {version}"
    wheels = locked.get("wheels")
    sdist = locked.get("sdist")
    files: dict[str, bytes] = {}
    metadata = ""
    source = ""
    if isinstance(wheels, list) and wheels:
        wheel = pick_wheel(wheels)
        source = wheel["url"]
        members = zip_files(verified(wheel["url"], wheel["hash"], cache, where))
        metadata = next(
            (
                decode(data, where)
                for path, data in members.items()
                if path.count("/") == 1 and path.endswith(".dist-info/METADATA")
            ),
            "",
        )
        files = {
            path: data
            for path, data in members.items()
            if (".dist-info/licenses/" in path)
            or (
                path.count("/") == 1
                and path.split("/")[0].endswith(".dist-info")
                and is_licence_file(path)
            )
        }
        if not files:
            files = {path: data for path, data in members.items() if is_licence_file(path)}
    if not files and isinstance(sdist, dict):
        members = tar_files(
            verified(str(sdist["url"]), str(sdist["hash"]), cache, where),
            lambda path: is_licence_file(path) or path.endswith("/PKG-INFO"),
        )
        if not metadata:
            metadata = next(
                (
                    decode(d, where)
                    for p, d in members.items()
                    if p.count("/") == 1 and p.endswith("/PKG-INFO")
                ),
                "",
            )
        files = {p: d for p, d in members.items() if is_licence_file(p)}
        if files:
            source = str(sdist["url"])
    licence = python_licence(metadata) if metadata else "not declared"
    if not files:
        return override_entry("python", name, version, licence, overrides, cache)
    texts = tuple(
        (path, normalise_text(decode(files[path], f"{where} {path}"), path))
        for path in sorted(files)
    )
    return Entry("python", name, version, licence, source, texts)


def npm_entry(
    entry: notices_coverage.NpmEntry,
    overrides: dict[tuple[str, str, str], Override],
    cache: Path,
) -> Entry:
    where = f"npm `{entry.name}` {entry.version}"
    if not entry.resolved or not entry.integrity:
        raise GenerationError(f"{where}: the lockfile records no resolved URL or integrity")
    members = tar_files(
        verified(entry.resolved, entry.integrity, cache, where),
        lambda path: (
            path.count("/") == 1 and (is_licence_file(path) or path.endswith("/package.json"))
        ),
    )
    licence = entry.license
    if not licence:
        manifest = next((d for p, d in members.items() if p.endswith("/package.json")), b"{}")
        declared = json.loads(manifest).get("license", "")
        licence = declared.get("type", "") if isinstance(declared, dict) else str(declared)
    licence = one_line(licence) or "not declared"
    files = {p: d for p, d in members.items() if is_licence_file(p)}
    if not files:
        return override_entry("npm", entry.name, entry.version, licence, overrides, cache)
    texts = tuple(
        (path, normalise_text(decode(files[path], f"{where} {path}"), path))
        for path in sorted(files)
    )
    return Entry("npm", entry.name, entry.version, licence, entry.resolved, texts)


def override_entry(
    ecosystem: str,
    name: str,
    version: str,
    licence: str,
    overrides: dict[tuple[str, str, str], Override],
    cache: Path,
) -> Entry:
    key = (ecosystem, name, version)
    override = overrides.get(key)
    if override is None:
        raise GenerationError(
            f"{describe(key)}: its lock-recorded artifacts carry no licence file and "
            f"{OVERRIDES.name} has no override for it"
        )
    texts = tuple(
        (url, normalise_text(decode(verified(url, sha, cache, describe(key)), url), url))
        for url, sha in override.files
    )
    source = f"upstream, pinned in scripts/{OVERRIDES.name}"
    return Entry(ecosystem, name, version, licence, source, texts)


def generate(cache: Path, root: Path = REPO_ROOT) -> str:
    lock = json.loads((root / "web" / "package-lock.json").read_text())
    python = runtime_python_packages(root)
    npm = notices_coverage.npm_production_entries(lock)
    expected = expected_entries(python, [(e.name, e.version) for e in npm])
    overrides = load_overrides(root / "scripts" / OVERRIDES.name)
    problems = override_problems(overrides, expected)
    if problems:
        raise GenerationError("; ".join(problems))
    by_key = {(o.ecosystem, o.package, o.version): o for o in overrides}
    locked = uv_lock_packages(root / "uv.lock")
    entries = []
    for name, version in python:
        if (name, version) not in locked:
            raise GenerationError(f"python `{name}` {version}: not in uv.lock")
        entries.append(python_entry(name, version, locked[(name, version)], by_key, cache))
    entries += [npm_entry(entry, by_key, cache) for entry in npm]
    return render(entries)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else None)
    parser.add_argument(
        "--check", action="store_true", help="exit 1 if the committed file is stale"
    )
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument(
        "--cache-dir", type=Path, help="keep downloads here (default: a temporary directory)"
    )
    args = parser.parse_args(argv)

    with tempfile.TemporaryDirectory() as scratch:
        cache = args.cache_dir or Path(scratch)
        try:
            text = generate(cache)
        except GenerationError as error:
            print(f"third_party_licenses: {error}", file=sys.stderr)
            return 1

    if args.check:
        current = args.output.read_text() if args.output.is_file() else ""
        if current != text:
            stale = coverage({e.key for e in parse(text)}, current)
            print(
                f"{args.output.name} is not what the lockfiles generate. Regenerate it with "
                "`uv run python scripts/third_party_licenses.py`. "
                f"Missing: {stale.missing[:5]}; not in the lockfiles: {stale.unexpected[:5]}",
                file=sys.stderr,
            )
            return 1
        return 0
    args.output.write_text(text)
    entries = parse(text)
    counts = Counter(entry.ecosystem for entry in entries)
    print(f"wrote {args.output.name}: {dict(sorted(counts.items()))}, {len(text)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
